version: '3'
services:
  dbservice:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

    volumes:
      - ./data:/var/lib/mysql

    ports:
      - 3306:3306
    networks:
      - bootapp

  appservice:
    build: ./
    depends_on:
      - dbservice
    environment:
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.url=jdbc:mysql://dbservice:3306/blog_app?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=password
	  - spring.jpa.properties.hibernate.dialecet=org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.jpa.hibernate.ddl-auto=update
    ports:
      - 8085:8090

    networks:
      - bootapp

networks:
  bootapp:
